import{a as q,S as E,i as n}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",R="54777816-6525979b388f506499e8016c2",f=15;async function m(r,t=1){return(await q.get(M,{params:{key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f}})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".js-loader"),p=document.querySelector(".load-more"),B=new E(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:c,comments:P,downloads:v})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${c}</p>
          <p class="info-item"><b>Comments</b> ${P}</p>
          <p class="info-item"><b>Downloads</b> ${v}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){g.innerHTML=""}function b(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function w(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}const S=document.querySelector(".form"),O=document.querySelector(".load-more");let d="",a=1,l=0;S.addEventListener("submit",x);O.addEventListener("click",A);async function x(r){r.preventDefault();const t=r.currentTarget.elements["search-text"].value.trim();if(!t){n.warning({message:"Please enter a search query.",position:"topRight"});return}d=t,a=1,l=0,$(),u(),b();try{const s=await m(d,a);l=s.totalHits;const i=s.hits;if(!i||i.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(i);const e=Math.ceil(l/f);a<e?w():(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),S.reset()}}async function A(){a+=1,b(),u();try{const t=(await m(d,a)).hits;y(t),_();const s=Math.ceil(l/f);a<s?w():(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}function _(){const r=document.querySelector(".gallery-item");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
